### PR TITLE
#139 Upgrade-to-0.26.2

### PR DESCRIPTION
**Pull request by pwilken**
@solidnerd could you merge  #138, #136 and then this #139 pls.

Thanks a lot :)

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey @pwilken,

thanks for your work. I'll accept your pr but it's in queue waiting for the releases before you. You will need to rebase when `0.26.1` will get out.

**Review by solidnerd — COMMENTED** [review]
Could you rebase your pr to get the latest changes ?

**Comment by solidnerd** [comment]
ping @pwilken

**Comment by pwilken** [comment]
@solidnerd done. Thanks for your work 👍

**Pull request merged**
