### PR TITLE
feat: upgrade bookstack to 0.30.2

### PR DESCRIPTION
**Pull request by Weasy666**

### CODE REVIEW

**Review by baskoopmans — APPROVED** [review]
Looking good!

**Comment by namxam** [comment]
Would be awesome to merge and release it, as draw.io integration is now completly broken and can no longer be used.

**Comment by JHenneberg** [comment]
Looks good but unfortunately it was not pulled in time and now it is not up-to-date anymore

**Comment by Weasy666** [comment]
I can easily change this to the newest version, but i don't want to invest my time if it stays unmerged.
@solidnerd will you merge this in time, if i update this PR to the newest Bookstack version?

**Comment by JHenneberg** [comment]
@Weasy666 Sure I understand. His last contribution was on the 9th so maybe he just missed the PR.

**Comment by Weasy666** [comment]
That is why i pinged him. But still no answer 🤷‍♂️

**Comment by solidnerd** [comment]
Hey, 
sorry for my delayed response. I had in the last weeks a lot of to-dos on my personal site so that I can't get to do the maintenance here. I'll start now again and appreciate every pull request.

**Comment by Weasy666** [comment]
Great to hear from you again!

**Pull request merged**
