### PR TITLE
updated .env to 29.1

### PR DESCRIPTION
**Pull request by JHenneberg**

### CODE REVIEW

**Comment by ssddanbrown** [comment]
I would suggest not passing through all `.env` options though like this unless required, It has potential to cause side-effects or introduce the likelihood of issues if I need to make breaking changes plus makes this harder to maintain. BookStack should read these options from the environment if they exist, meaning you should be able to define these as docker env options unless I'm otherwise mistaken.

**Comment by JHenneberg** [comment]
I am not really familiar with docker. I missed a few ldap settings and wanted to add them. Thinking about others too I added all options :). I don't understand how an alternative should look like. From my understanding the .env is written with the `-e`  I pass in the `docker run` command or am I mistaken? All passed environment variable overwrite then the entries in `entrypoint.sh` otherwise default value is taken.

The only other option would be to extract `.env` as a volume and edit it from there, but it is in the root folder. 
Edit: Looks like you can also mount a single file as a volume.

An other option is to login into the docker and overwrite it in there but then it's not persistent.

**Comment by ssddanbrown** [comment]
> From my understanding the .env is written with the -e I pass in the docker run command or am I mistaken? All passed environment variable overwrite then the entries in entrypoint.sh otherwise default value is taken.

No, You're not mistaken, that's what going on here but BookStack should **_also_** read the variables from the system/process environment. Therefore, for any options missing in the `.env` file these scripts produce, you should be able to define the option direction as a docker env option and BookStack will still pick it up, as long as it's named correctly.

**Comment by solidnerd** [comment]
@ssddanbrown So this would mean that don't need to write any values in .env and can pass them all through docker environment variables. This would be really nice and reduce the complexity.

I implemented this, because I wasn't sure that bookstack needs a `.env` to work as expected.

**Comment by ssddanbrown** [comment]
@solidnerd Give it a test to be sure, But I think that's how it works. It might depend on if the docker-defined env options reach the running php process as expected. 

> I implemented this, because I wasn't sure that bookstack needs a .env to work as expected.

I've never tried running BookStack without it without to be honest, not sure if it will work or not. You can always do both and keep the `.env` for the base options (Or ones you have now), then people just pass docker env values for additional options.

**Comment by JHenneberg** [comment]
I was able to setup the docker bookstack on a windows machine and mounting the `.env`. The `.env`-file has to be already created before running the docker otherwise a folder name .env will be created instead. Maybe this is something that should be mentioned in the `README.md` @solidnerd 

```
docker run -d --net bookstack_nw --mount type=bind,source=e:/Docker-images/bookstack/.env,target=/var/www/bookstack/.env -v e:/Docker-images/bookstack/public/uploads:/var/www/bookstack/public/uploads -v e:/Docker-images/bookstack/storage/uploads:/var/www/bookstack/storage/uploads -e DB_HOST=bookstack_db:3306 -e DB_DATABASE=bookstack -e DB_USERNAME=bookstack -e DB_PASSWORD=secret -p 8080:8080 --name="bookstack_29.1" solidnerd/bookstack:0.29.1
pause


```

**Comment by solidnerd** [comment]
Hey @JHenneberg,
I'm currently a little bit confused what your pull request tries to solve now. :neckbeard:  So our in discussion with @ssddanbrown we found out that aren't need to set those variables in the image. Also you had different solultion for mounting the env on a windows host. 

Could you create a separate pull request for the mount of the environment from this commint. https://github.com/solidnerd/docker-bookstack/pull/191#issuecomment-625658677 

I would close this pull request than if you are also fine with it.

WDYT @JHenneberg

**Comment by JHenneberg** [comment]
I just kept it open to discuss this. When it is closed its flying under the radar.

I will make an PR later today.

**Pull request closed without merging**
