### PR TITLE
make all variables available into docker-entrypoint.sh

### PR DESCRIPTION
**Pull request by gandarez**

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Good effort on the pull request but I'm not sure defining all variables is really needed, You should just be able to define environment variables with the same name and BookStack will pick them up.

Having all variables here might just make this harder to maintain and cause side-effects where unexpected defaults are defined.

**Comment by gandarez** [comment]
@ssddanbrown I followed the environment example in the original repository. I think the problem I have covered is that the docker image in docker hub is missing those variables.

https://github.com/BookStackApp/BookStack/blob/master/.env.example.complete

**Comment by skabbes** [comment]
I'm a brand new user today of Bookstack using this docker images too, I hit the exact same issue with AVATAR_URL today :(

But was pleasantly surprised that the other env vars worked just fine.

**Comment by woprandi** [comment]
@ssddanbrown Define variable in the` docker-compose.yml` isn't enough. For example I can't define `LDAP_DISPLAY_NAME_ATTRIBUTE` in the `docker-compose.yml` file

**Comment by gandarez** [comment]
When it could be merged?

**Pull request closed without merging**
