### PR TITLE
Update Bookstack to 0.22.0

### PR DESCRIPTION
**Pull request by pschmitt**

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey @pschmitt,
it seems they were roating all the base images on the docker hub right now. So the `php:7.1-apache` is stretched based now.

**Comment by pschmitt** [comment]
@solidnerd I'm aware of the change, that's precisely why I added 4d28d22

**Comment by solidnerd** [comment]
I think we need also define the baseimage distro. So that won't happen in future. But thanks for this. I will approve your PR and make the other changes later than.

**Comment by pschmitt** [comment]
Thanks.
`php:7.1-apache-stretch` should work just fine.

**Pull request merged**
