### PR TITLE
Generate APP_KEY without using Laravel artisan command

### LINKED ISSUE #35: container appears to be waiting for some kind of user input
I'm trying to get bookstack setup in docker using an external mariaDB instance on another server. However when the container starts the logs seem to indicate that it's waiting for some kind of input and the application never comes up. I've got the following environment variables setup.

DB_HOST
DB_DATABASE
DB_USERNAME
DB_PASSWORD

I'm sure I'm missing something...

5/12/2017 11:07:59 AM Do you really wish to run this command? (yes/no) [no]:
5/12/2017 11:17:04 AM > 2017-05-12T16:17:43.511073944Z wait-for-db: waiting for db.domain.net:3306
5/12/2017 11:17:44 AMwait-for-db: done
5/12/2017 11:17:44 AMDo not run Composer as root/super user! See https://getcomposer.org/root for details
5/12/2017 11:17:44 AM> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
5/12/2017 11:17:44 AM> php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
5/12/2017 11:17:44 AMLoading composer repositories with package information
5/12/2017 11:17:44 AMInstalling dependencies (including require-dev) from lock file
5/12/2017 11:17:44 AMNothing to install or update
5/12/2017 11:17:44 AMGenerating autoload files
5/12/2017 11:17:44 AM> Illuminate\Foundation\ComposerScripts::postInstall
5/12/2017 11:17:44 AM> php artisan optimize
5/12/2017 11:17:44 AMGenerating optimized class loader
5/12/2017 11:17:45 AMThe compiled services file has been removed.
5/12/2017 11:17:45 AM> php artisan cache:clear
5/12/2017 11:17:45 AMCache cleared successfully.
5/12/2017 11:17:45 AM> php artisan view:clear
5/12/2017 11:17:46 AMCompiled views cleared!
5/12/2017 11:17:46 AM**************************************
5/12/2017 11:17:46 AM*     Application In Production!     *
5/12/2017 11:17:46 AM**************************************
5/12/2017 11:17:46 AM
5/12/2017 11:17:46 AM Do you really wish to run this command? (yes/no) [no]:

### PR DESCRIPTION
**Pull request by fklingler**
Removes the `php artisan key:generate` command which can be problematic
when running the container with a console attached.

Fixes #35

### CODE REVIEW

**Comment by solidnerd** [comment]
@fklingler Hey, I'm quite not sure if this is the correct way. Because every time you restart the container a new APP_KEY will be generated. So what I understand is that the APP_KEY will be used to encrypt data in the Database. So when it's true. It's not a good idea to generate the APP_KEY everytime new.

**Comment by fklingler** [comment]
My bad, the key is generated each time, but the .env file is written only once so it does work correctly, but it could be written more cleanly. I'll fix that now.

**Comment by fklingler** [comment]
It should be better now. Thanks for pointing that out!

**Comment by ssddanbrown** [comment]
@fklingler The `.env` file is written into the container through so you kind of expect it to be disposable at that point. It'll be destroyed at update unless you create a volume through to the BookStack files.

Overall I don't think the key itself really matters right now as I can't think of anywhere in BookStack that encryption is used (yet).

I could be wrong but it looks like @solidnerd has already set this up so you can provide the `APP_KEY` as an environment variable to the container which would be the proper way of getting around your issue.
As far as I can see, The changes in this pull request would actually prevent that functionality as the `APP_KEY` environment variable would be redefined in the script every time.

**Comment by fklingler** [comment]
Yes I do create a volume for the files.
If you don't, the current `.env` file will still be destroyed and this could be a problem. And the `php artisan key:generate` command is still executed at each build.

I don't think you can provide `APP_KEY` through an environment variable, I didn't see where this would be handled in the current files, but I could also be wrong.

The main problem still is #35. You should not use the `php artisan key:generate` command like that in a Dockerfile. This forces an interactive response and it can be a problem in some environments. Maybe there is an option with the `php artisan` command to force a `yes` answer, and not be blocked if there is no user interaction? (but this would not be sufficient, as I said earlier, the command is still executed at each build and the key generated this way)

**Comment by ssddanbrown** [comment]
> Yes I do create a volume for the files.
> If you don't, the current .env file will still be destroyed and this could be a problem.

That's okay but not everyone will want to mount a volume at the root of BookStack just to save the `.env` file. Destruction of the `.env` file should not be a problem if all configuration is supplied to the container as env variables.

> And the php artisan key:generate command is still executed at each build.

Yeah, I agree it would be better if this is changed to only run if no APP_KEY environment variable is passed.

> I don't think you can provide APP_KEY through an environment variable, I didn't see where this would be handled in the current files, but I could also be wrong.

Looking at the [entrypoint script here](https://github.com/solidnerd/docker-bookstack/blob/master/docker-entrypoint.sh#L16) looks like it accepts an environment variable for this.

> This forces an interactive response and it can be a problem in some environments.

100% agree. As with most artisan commands it does accept a `--no-interaction` flag which would be well suited here. Also should probably be added to the migration command.

**Comment by vdavid** [comment]
It does work with `--force` though. Use:
> `php artisan key:generate --force`.

**Pull request closed without merging**
