### PR TITLE
Update Dockerfile 21.11.3

### PR DESCRIPTION
**Pull request by reddexx**

### CODE REVIEW

**Comment by solidnerd** [comment]
Hey @reddexx, 
thanks for the contribution lets have the build running and I'll merge it.

**Comment by reddexx** [comment]
@solidnerd the test failed, the error can ignore?

**Comment by solidnerd** [comment]
@reddexx  Something has changed the bookstack app is not starting 

```
wait-for-db: waiting for mysql:3306
wait-for-db: done
Generating Key...

In Request.php line 334:

  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must
   be of type string, null given, called in /var/www/bookstack/vendor/laravel
  /framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php on
  line 32

```

**Comment by solidnerd** [comment]
Okay got it  APP_URL needs to be specified

```
APP_URL=http://localhost:${DEV_PORT:-8080}
```

**Comment by reddexx** [comment]
Can you Change this?

**Comment by solidnerd** [comment]
Already done 👍  waiting for rerun 💯

**Comment by solidnerd** [comment]
@reddexx  Thanks for your contribution. 💯  I'm gonna merge this

**Pull request merged**
