### PR TITLE
Updating Bookstack to 0.26.1

### PR DESCRIPTION
**Pull request by sardaukar**

### CODE REVIEW

**Review by tylwright — CHANGES_REQUESTED** [review]
You haven't changed the version in the following files:
- VERSION
- docker-compose.yml

I have #138 open to upgrade it to v0.26.0.  Once that gets merged up, I can write up v0.26.2, if you want.

**Comment by sardaukar** [comment]
I've updated the missing references. Not sure if you still want to merge this, but just having `docker-bookstack` updated either way would be great! :D

**Comment by solidnerd** [comment]
Hey @sardaukar,

thanks for your work. I'll accept the pr but it will need some more work. I really prefer a single commit for the upgrade. As well you should rebase when `0.26.0` is released so that we have a continuation in the pr for the releases.

**Comment by sardaukar** [comment]
I made it into a single commit, let me know when I can rebase from `0.26.0`.

**Comment by solidnerd** [comment]
Yep i'll do it.

Bruno Antunes <notifications@github.com> schrieb am Mo., 17. Juni 2019,
23:23:

**Comment by sardaukar** [comment]
@solidnerd hope it's ok now!

**Pull request merged**
